// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheSDKShop.Infrastructure.Models;

public partial class ProductReview
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public bool IsActive { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}