// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheSDKShop.Infrastructure.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ProductCode { get; set; }

    public int CategoryId { get; set; }

    public int? SubCategoryId { get; set; }

    public int SupplierId { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public virtual ProductCategory Category { get; set; }

    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    public virtual Supplier Supplier { get; set; }
}